version: 0.2
env:
  secrets-manager:
    LOGIN: 21234191Carpool:sonartoken
    HOST: 21234191Carpool:HOST
    Organization: 21234191Carpool:Organization
    Project: 21234191Carpool:Project
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install --upgrade pip
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - python --version
      - python sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi